# Generated by Django 5.2.3 on 2025-08-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
