# Generated by Django 5.2.3 on 2025-07-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_career_remove_jobapplication_job_delete_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='qualifications',
            field=models.TextField(blank=True),
        ),
    ]
