# Generated by Django 5.2.3 on 2025-07-01 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0002_orderedservice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderedService',
        ),
    ]
