# Generated by Django 5.2.3 on 2025-07-03 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_subscriber_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='confirmed',
        ),
    ]
