# Generated by Django 5.2.3 on 2025-07-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_remove_subscriber_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
