# Generated by Django 5.2.3 on 2025-07-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_subscriber_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='confirmation_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
