# Generated by Django 5.2.3 on 2025-07-03 17:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_subscriber_confirmation_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='subscribed_at',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='confirmation_token',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
