# Generated by Django 5.2.3 on 2025-07-05 20:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_remove_subscriber_subscribed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='confirmation_token',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='created_at',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='subscribed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
