# Generated by Django 5.2.3 on 2025-07-28 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, help_text="Use icon class like 'fa-solid fa-code'", max_length=100, null=True)),
                ('icon_svg', models.TextField(blank=True, help_text='Paste complete SVG code here (starting with <svg...>)', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_svg', models.TextField(blank=True, help_text='Paste complete SVG code here', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feature_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='services.featuresection')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='platforms/logos/')),
                ('platform_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='services.platformsection')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, help_text="Use icon class like 'fa-solid fa-code'", max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='process/images/')),
                ('icon_svg', models.TextField(blank=True, help_text='Paste complete SVG code here', null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='services.processsection')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.AddField(
            model_name='processsection',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_sections', to='services.service'),
        ),
        migrations.AddField(
            model_name='platformsection',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_sections', to='services.service'),
        ),
        migrations.CreateModel(
            name='OrderedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_services', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=200, null=True)),
                ('subheading', models.TextField(blank=True, null=True)),
                ('button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('button_link', models.URLField(blank=True, null=True)),
                ('background_image', models.ImageField(upload_to='hero_images/')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hero_section', to='services.service')),
            ],
        ),
        migrations.AddField(
            model_name='featuresection',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_sections', to='services.service'),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('button_link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='about_images/')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='about_section', to='services.service')),
            ],
        ),
    ]
