# Generated by Django 5.2.3 on 2025-07-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_orderedservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='Paste complete SVG code here (starting with <svg...>)', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, help_text="Use icon class like 'fa-solid fa-code'", max_length=100, null=True),
        ),
    ]
