# Generated by Django 5.2.3 on 2025-07-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_about_faq_featuresection_hero_platformsection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstep',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='Paste complete SVG code here', null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='process/images/'),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='icon',
            field=models.CharField(blank=True, help_text="Use icon class like 'fa-solid fa-code'", max_length=100, null=True),
        ),
    ]
