# Generated by Django 5.2.3 on 2025-07-28 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('author', models.CharField(max_length=100)),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='author_images/')),
                ('author_bio', models.TextField(blank=True, null=True)),
                ('category', models.CharField(default='Uncategorized', max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_id', models.CharField(help_text="Used in <a href='#id'> and <h4 id='...'>", max_length=100)),
                ('heading_title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='blog.blogpost')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
