# Generated by Django 5.2.3 on 2025-07-08 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=100),
        ),
    ]
