# Generated by Django 5.2.3 on 2025-07-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_recentpost_blogsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author_bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='author_images/'),
        ),
    ]
