# Generated by Django 5.2.3 on 2025-07-07 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio_images/')),
                ('project_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OverviewSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Overview', max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='overview/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overview_sections', to='portfolio.portfolioproject')),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(upload_to='hero/')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hero', to='portfolio.portfolioproject')),
            ],
        ),
        migrations.CreateModel(
            name='FullWidthImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fullwidth/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fullwidth_images', to='portfolio.portfolioproject')),
            ],
        ),
        migrations.CreateModel(
            name='RequirementsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Requirements', max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='requirements/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements_sections', to='portfolio.portfolioproject')),
            ],
        ),
        migrations.CreateModel(
            name='ResultSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Result', max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_sections', to='portfolio.portfolioproject')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Solutions', max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='solutions/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions_sections', to='portfolio.portfolioproject')),
            ],
        ),
        migrations.CreateModel(
            name='TechnologySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Our Technology Stack', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technology_section', to='portfolio.portfolioproject')),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='tech_icons/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='portfolio.technologysection')),
            ],
        ),
    ]
