# Generated by Django 5.2.3 on 2025-07-05 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_fullwidthimage_hero_overviewsection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='button_link',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='description',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='heading',
        ),
    ]
